### ISSUE TITLE
The project is not built correctly

### ISSUE THREAD

**Issue by Angelmmiguel** [bitnami/hex#251]
We're getting exceptions during the compilation process:

```lerna ERR! yarn run build stderr:
15:02:23 events.js:165
15:02:23       throw er; // Unhandled 'error' event
15:02:23       ^
15:02:23 
15:02:23 Error: watch /app/packages/hex-docz/node_modules/@bitnami/hex-react/node_modules/istanbul-api/node_modules/@babel/types/lib/definitions ENOSPC
15:02:23     at FSWatcher.start (fs.js:1402:19)
15:02:23     at Object.fs.watch (fs.js:1428:11)
15:02:23     at createFsWatchInstance (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:37:15)
15:02:23     at setFsWatchListener (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:80:15)
15:02:23     at FSWatcher.NodeFsHandler._watchWithNodeFs (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:232:14)
15:02:23     at FSWatcher.NodeFsHandler._handleDir (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:414:19)
15:02:23     at FSWatcher.<anonymous> (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:462:19)
15:02:23     at FSWatcher.<anonymous> (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:467:16)
15:02:23     at FSReqWrap.oncomplete (fs.js:171:5)
15:02:23 Emitted 'error' event at:
15:02:23     at FSWatcher._handleError (/app/packages/hex-docz/node_modules/chokidar/index.js:260:10)
15:02:23     at createFsWatchInstance (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:39:5)
15:02:23     at setFsWatchListener (/app/packages/hex-docz/node_modules/chokidar/lib/nodefs-handler.js:80:15)
15:02:23     [... lines matching original stack trace ...]
15:02:23     at FSReqWrap.oncomplete (fs.js:171:5)
15:02:23 error Command failed with exit code 1.```

This error has prevented the images to be uploaded correctly.

**Comment by Angelmmiguel** [comment]
For the record, I deployed the v4.0.0. To fix it, I've just ignored the `hex-docz` package during the compilation.
